# Name your workflow
name: Run spotlight_getters and Save Data Folder

# Define when the workflow should run
on:
  push:
    branches: [ main ]  # Runs on pushes to the main branch
  workflow_dispatch:      # Allows you to run it manually from the Actions tab

# Define the jobs to run
jobs:
  run-and-archive:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out your repository code so the script is available
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up your desired Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: (Optional but recommended) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script. The script itself handles creating the 'data' folder and files.
      - name: Run the python script
        run: python spotlight_getters.py

      # Step 5: Upload the entire 'data' folder as an artifact
      - name: Upload data folder
        uses: actions/upload-artifact@v4
        with:
          name: generated-data  # The name of the downloadable artifact zip
          path: data/          # The path to the folder to upload